{{-- packages/gunreip/laravel-translation-workbench/resources/views/pages/tw-graph/diagnostics.blade.php --}}

<x-layouts::app :title="__('TW-Graph Diagnostics')">
    @php
        $twGraphReportJsonPath = storage_path('translation-workbench/reports/tw-graph-tests/latest.json');
        $twGraphReportHtmlPath = storage_path('translation-workbench/reports/tw-graph-tests/latest.html');
        $twGraphReport = null;
        $twGraphReportError = null;

        if (is_file($twGraphReportJsonPath)) {
            $twGraphReport = json_decode((string) file_get_contents($twGraphReportJsonPath), true);

            if (!is_array($twGraphReport)) {
                $twGraphReport = null;
                $twGraphReportError = __('The latest TW-Graph test report could not be decoded.');
            }
        }

        $twGraphChecks = collect((array) data_get($twGraphReport, 'checks', []));
        $twGraphGroups = collect((array) data_get($twGraphReport, 'groups', []));
        $twGraphStatus = (string) data_get($twGraphReport, 'status', 'missing');
        $twGraphStatusColor = match ($twGraphStatus) {
            'passed' => 'green',
            'failed' => 'red',
            default => 'zinc',
        };
    @endphp

    <flux:card class="translation-workbench">
        <x-ui.headers.page
            :title="__('TW-Graph Diagnostics')"
            :description="__('Last explicit TW-Graph check report generated by clear:project --tw-graph-tests.')"
        />

        <div class="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_32rem]">
            <flux:callout
                :color="$twGraphStatusColor"
                icon="clipboard-check"
            >
                <flux:callout.heading class="flex flex-wrap items-center gap-2">
                    <span>{{ __('Latest TW-Graph checks') }}</span>
                    <flux:badge
                        size="sm"
                        :color="$twGraphStatusColor"
                    >
                        {{ $twGraphStatus }}
                    </flux:badge>
                </flux:callout.heading>

                <flux:callout.text>
                    @if ($twGraphReport === null)
                        <p class="text-sm text-zinc-600 dark:text-zinc-300">
                            {{ $twGraphReportError ?? __('No TW-Graph test report exists yet.') }}
                        </p>
                        <pre class="mt-3 overflow-x-auto rounded-md bg-zinc-950 p-3 text-xs text-zinc-100"><code>php artisan clear:project --tw-graph-tests</code></pre>
                    @else
                        <dl class="mt-3 grid gap-3 text-sm sm:grid-cols-3">
                            <div>
                                <dt
                                    class="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
                                    {{ __('Generated at') }}
                                </dt>
                                <dd class="mt-1 font-mono text-xs text-zinc-700 dark:text-zinc-200">
                                    {{ data_get($twGraphReport, 'generated_at') }}
                                </dd>
                            </div>
                            <div>
                                <dt
                                    class="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
                                    {{ __('Checks') }}
                                </dt>
                                <dd class="mt-1 text-zinc-700 dark:text-zinc-200">
                                    {{ $twGraphChecks->count() }}
                                </dd>
                            </div>
                            <div>
                                <dt
                                    class="text-xs font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
                                    {{ __('Report file') }}
                                </dt>
                                <dd class="mt-1 font-mono text-xs text-zinc-700 dark:text-zinc-200">
                                    {{ str_replace(base_path() . DIRECTORY_SEPARATOR, '', $twGraphReportJsonPath) }}
                                </dd>
                            </div>
                        </dl>
                    @endif
                </flux:callout.text>
            </flux:callout>

            <flux:callout
                color="sky"
                icon="terminal"
            >
                <flux:callout.heading>
                    {{ __('Run command') }}
                </flux:callout.heading>
                <flux:callout.text>
                    <p class="text-sm text-zinc-600 dark:text-zinc-300">
                        {{ __('The diagnostics page is read-only. Run the checks deliberately from the console, then reload this page.') }}
                    </p>
                    <pre class="mt-3 overflow-x-auto rounded-md bg-zinc-950 p-3 text-xs text-zinc-100"><code>php artisan clear:project --tw-graph-tests</code></pre>
                    @if (is_file($twGraphReportHtmlPath))
                        <p class="mt-3 break-all font-mono text-xs text-zinc-500 dark:text-zinc-400">
                            {{ str_replace(base_path() . DIRECTORY_SEPARATOR, '', $twGraphReportHtmlPath) }}
                        </p>
                    @endif
                </flux:callout.text>
            </flux:callout>
        </div>

        @if ($twGraphReport !== null)
            @if ($twGraphGroups->isNotEmpty())
                <flux:callout
                    class="mt-6"
                    color="zinc"
                    icon="layout-list"
                >
                    <flux:callout.heading>
                        {{ __('Group Summary') }}
                    </flux:callout.heading>
                    <flux:callout.text>
                        <div class="mt-4 overflow-x-auto rounded-lg border border-zinc-200 dark:border-zinc-700">
                            <table class="min-w-full divide-y divide-zinc-200 text-sm dark:divide-zinc-700">
                                <thead
                                    class="bg-zinc-50 text-left text-xs uppercase tracking-wide text-zinc-500 dark:bg-zinc-900 dark:text-zinc-400"
                                >
                                    <tr>
                                        <th class="px-3 py-2">{{ __('Group') }}</th>
                                        <th class="px-3 py-2">{{ __('Status') }}</th>
                                        <th class="px-3 py-2">{{ __('Checks') }}</th>
                                        <th class="px-3 py-2">{{ __('Tests') }}</th>
                                        <th class="px-3 py-2">{{ __('Assertions') }}</th>
                                        <th class="px-3 py-2">{{ __('Duration') }}</th>
                                    </tr>
                                </thead>
                                <tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">
                                    @foreach ($twGraphGroups as $twGraphGroup)
                                        @php
                                            $groupStatus = (string) data_get($twGraphGroup, 'status', 'unknown');
                                            $groupStatusColor =
                                                $groupStatus === 'passed'
                                                    ? 'green'
                                                    : ($groupStatus === 'failed'
                                                        ? 'red'
                                                        : 'zinc');
                                        @endphp

                                        <tr>
                                            <td class="px-3 py-2 text-zinc-900 dark:text-zinc-100">
                                                <span class="font-medium">{{ data_get($twGraphGroup, 'name') }}</span>
                                                <span class="mt-1 block text-xs text-zinc-500 dark:text-zinc-400">
                                                    {{ data_get($twGraphGroup, 'description') }}
                                                </span>
                                            </td>
                                            <td class="px-3 py-2">
                                                <flux:badge
                                                    size="sm"
                                                    :color="$groupStatusColor"
                                                >
                                                    {{ $groupStatus }}
                                                </flux:badge>
                                            </td>
                                            <td class="px-3 py-2 font-mono text-xs text-zinc-600 dark:text-zinc-300">
                                                {{ data_get($twGraphGroup, 'checks') }}
                                            </td>
                                            <td class="px-3 py-2 font-mono text-xs text-zinc-600 dark:text-zinc-300">
                                                {{ data_get($twGraphGroup, 'tests') }}
                                            </td>
                                            <td class="px-3 py-2 font-mono text-xs text-zinc-600 dark:text-zinc-300">
                                                {{ data_get($twGraphGroup, 'assertions') }}
                                            </td>
                                            <td class="px-3 py-2 font-mono text-xs text-zinc-600 dark:text-zinc-300">
                                                {{ data_get($twGraphGroup, 'duration_ms') }} ms
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </flux:callout.text>
                </flux:callout>
            @endif

            <flux:callout
                class="mt-6"
                color="zinc"
                icon="list-checks"
            >
                <flux:callout.heading>
                    {{ __('Check Results') }}
                </flux:callout.heading>
                <flux:callout.text>
                    <div class="mt-4 overflow-x-auto rounded-lg border border-zinc-200 dark:border-zinc-700">
                        <table class="min-w-full divide-y divide-zinc-200 text-sm dark:divide-zinc-700">
                            <thead
                                class="bg-zinc-50 text-left text-xs uppercase tracking-wide text-zinc-500 dark:bg-zinc-900 dark:text-zinc-400"
                            >
                                <tr>
                                    <th class="px-3 py-2">{{ __('Check') }}</th>
                                    <th class="px-3 py-2">{{ __('Status') }}</th>
                                    <th class="px-3 py-2">{{ __('Duration') }}</th>
                                    <th class="px-3 py-2">{{ __('Summary') }}</th>
                                    <th class="px-3 py-2">{{ __('Command') }}</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-zinc-200 dark:divide-zinc-700">
                                @foreach ($twGraphChecks as $twGraphCheck)
                                    @php
                                        $checkStatus = (string) data_get($twGraphCheck, 'status', 'unknown');
                                        $checkStatusColor =
                                            $checkStatus === 'passed'
                                                ? 'green'
                                                : ($checkStatus === 'failed'
                                                    ? 'red'
                                                    : 'zinc');
                                    @endphp

                                    <tr>
                                        <td
                                            class="px-3 py-2 text-zinc-900 dark:text-zinc-100"
                                            title="{{ data_get($twGraphCheck, 'output') }}"
                                        >
                                            <span class="font-medium">{{ data_get($twGraphCheck, 'name') }}</span>
                                            <span class="mt-1 block text-xs text-zinc-500 dark:text-zinc-400">
                                                {{ data_get($twGraphCheck, 'description') }}
                                            </span>
                                        </td>
                                        <td class="px-3 py-2">
                                            <flux:badge
                                                size="sm"
                                                :color="$checkStatusColor"
                                            >
                                                {{ $checkStatus }}
                                            </flux:badge>
                                        </td>
                                        <td class="px-3 py-2 font-mono text-xs text-zinc-600 dark:text-zinc-300">
                                            {{ data_get($twGraphCheck, 'duration_ms') }} ms
                                        </td>
                                        <td class="px-3 py-2 text-zinc-700 dark:text-zinc-200">
                                            {{ data_get($twGraphCheck, 'summary') }}
                                        </td>
                                        <td class="px-3 py-2 font-mono text-xs text-zinc-600 dark:text-zinc-300">
                                            {{ data_get($twGraphCheck, 'command') }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </flux:callout.text>
            </flux:callout>
        @endif
    </flux:card>
</x-layouts::app>
