<?php

namespace Gunreip\TranslationWorkbench\Support\TwGraph\Documentation;

use Livewire\Livewire;

/** Explicit destinations: only tab IDs from this catalog are used for navigation. */
final class DocumentationLinks
{
    public const COMPONENTS = ['parts.chain', 'parts.end', 'parts.fusion', 'parts.sideways', 'parts.start', 'strang.branch-end', 'strang.branch-left', 'strang.branch-right', 'strang.flow-if', 'strang.flow-if-else', 'strang.flow-if-elseif', 'strang.flow-if-elseif-multi', 'strang.flow-if-ternary', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case', 'strang.merge-left', 'strang.merge-right', 'strang.rekey-source-left', 'strang.rekey-source-right', 'strang.rekey-target-left', 'strang.rekey-target-right', 'strang.trunk'];

    public const EXAMPLES = [
        'canvas.canvas-default-trunk' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-default-trunk'], 'label' => 'Canvas → Default + trunk', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-default-trunk'],
        'canvas.canvas-coordinates' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-coordinates'], 'label' => 'Canvas → Canvas + coord', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-coordinates'],
        'canvas.canvas-height' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-height'], 'label' => 'Canvas → Canvas height', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-height'],
        'canvas.canvas-props-line' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-props', 'canvas_canvas_props' => 'canvas-props-line'], 'label' => 'Canvas → Canvas + props → Line width', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-props-line'],
        'canvas.canvas-props-stem-length' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-props', 'canvas_canvas_props' => 'canvas-props-stem-length'], 'label' => 'Canvas → Canvas + props → Stem length', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-props-stem-length'],
        'canvas.canvas-props-node-size' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-props', 'canvas_canvas_props' => 'canvas-props-node-size'], 'label' => 'Canvas → Canvas + props → Node size', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-props-node-size'],
        'canvas.canvas-props-cap-length' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-props', 'canvas_canvas_props' => 'canvas-props-cap-length'], 'label' => 'Canvas → Canvas + props → Cap length', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-props-cap-length'],
        'canvas.canvas-props-min-width' => ['tabs' => ['main' => 'idea-to-paper-canvas', 'canvas_index' => 'canvas-props', 'canvas_canvas_props' => 'canvas-props-min-width'], 'label' => 'Canvas → Canvas + props → Min width', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.canvas.canvas-props-min-width'],
        'parts.parts-start' => ['tabs' => ['main' => 'idea-to-paper-parts', 'parts_index' => 'idea-to-paper-parts-start'], 'label' => 'Parts → Start', 'components' => ['parts.start'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.parts.parts-start'],
        'parts.parts-end' => ['tabs' => ['main' => 'idea-to-paper-parts', 'parts_index' => 'idea-to-paper-parts-end'], 'label' => 'Parts → End', 'components' => ['parts.end'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.parts.parts-end'],
        'parts.parts-sideways' => ['tabs' => ['main' => 'idea-to-paper-parts', 'parts_index' => 'idea-to-paper-parts-sideways'], 'label' => 'Parts → Sideways', 'components' => ['parts.sideways'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.parts.parts-sideways'],
        'parts.parts-chain' => ['tabs' => ['main' => 'idea-to-paper-parts', 'parts_index' => 'idea-to-paper-parts-chain'], 'label' => 'Parts → Chain', 'components' => ['parts.chain'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.parts.parts-chain'],
        'parts.parts-fusion' => ['tabs' => ['main' => 'idea-to-paper-parts', 'parts_index' => 'idea-to-paper-parts-fusion'], 'label' => 'Parts → Fusion', 'components' => ['parts.fusion'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.parts.parts-fusion'],
        'strang.trunk.trunk-default' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-default'], 'label' => 'Strang Trunk → Default', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-default'],
        'strang.trunk.trunk-stem-count' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-stem-count'], 'label' => 'Strang Trunk → Stem count', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-stem-count'],
        'strang.trunk.trunk-stem-lengths' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-stem-lengths'], 'label' => 'Strang Trunk → Stem lengths', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-stem-lengths'],
        'strang.trunk.trunk-direction' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-direction'], 'label' => 'Strang Trunk → Direction', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-direction'],
        'strang.trunk.trunk-start-overview' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-overview'], 'label' => 'Strang Trunk → Start → Overview', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-overview'],
        'strang.trunk.trunk-start-compare' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-compare'], 'label' => 'Strang Trunk → Start → Start compare', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-compare'],
        'strang.trunk.trunk-start-default' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-default'], 'label' => 'Strang Trunk → Start → Start default', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-default'],
        'strang.trunk.trunk-start-long-start' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-long-start'], 'label' => 'Strang Trunk → Start → Start long start', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-long-start'],
        'strang.trunk.trunk-start-wide-labels' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-wide-labels'], 'label' => 'Strang Trunk → Start → Start wide labels', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-wide-labels'],
        'strang.trunk.trunk-start-spacing' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-spacing'], 'label' => 'Strang Trunk → Start → Start spacing', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-spacing'],
        'strang.trunk.trunk-start-colors' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start', 'strang_trunk_trunk_start' => 'trunk-start-colors'], 'label' => 'Strang Trunk → Start → Start colors', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-colors'],
        'strang.trunk.trunk-start-shift' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-start-shift'], 'label' => 'Strang Trunk → Start shift', 'components' => ['strang.merge-left', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-start-shift'],
        'strang.trunk.trunk-end-overview' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-end', 'strang_trunk_trunk_end' => 'trunk-end-overview'], 'label' => 'Strang Trunk → End → Overview', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-end-overview'],
        'strang.trunk.trunk-end-default' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-end', 'strang_trunk_trunk_end' => 'trunk-end-default'], 'label' => 'Strang Trunk → End → End default', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-end-default'],
        'strang.trunk.trunk-end-long-end' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-end', 'strang_trunk_trunk_end' => 'trunk-end-long-end'], 'label' => 'Strang Trunk → End → End long end', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-end-long-end'],
        'strang.trunk.trunk-end-wide-label' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-end', 'strang_trunk_trunk_end' => 'trunk-end-wide-label'], 'label' => 'Strang Trunk → End → End wide label', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-end-wide-label'],
        'strang.trunk.trunk-end-cap' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-end', 'strang_trunk_trunk_end' => 'trunk-end-cap'], 'label' => 'Strang Trunk → End → End cap', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-end-cap'],
        'strang.trunk.trunk-end-color' => ['tabs' => ['main' => 'idea-to-paper-trunk', 'strang_trunk_index' => 'trunk-end', 'strang_trunk_trunk_end' => 'trunk-end-color'], 'label' => 'Strang Trunk → End → End color', 'components' => ['strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.trunk.trunk-end-color'],
        'strang.merge.merge-default' => ['tabs' => ['main' => 'idea-to-paper-merge', 'strang_merge_index' => 'idea-to-paper-merge-base'], 'label' => 'Strang Merge → Default', 'components' => ['strang.merge-left', 'strang.merge-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.merge.merge-default'],
        'strang.merge.merge-start' => ['tabs' => ['main' => 'idea-to-paper-merge', 'strang_merge_index' => 'idea-to-paper-merge-start'], 'label' => 'Strang Merge → Merge start', 'components' => ['strang.merge-left', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.merge.merge-start'],
        'strang.merge.merge-mismatch' => ['tabs' => ['main' => 'idea-to-paper-merge', 'strang_merge_index' => 'idea-to-paper-merge-mismatch'], 'label' => 'Strang Merge → Merge mismatch', 'components' => ['strang.merge-left', 'strang.merge-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.merge.merge-mismatch'],
        'strang.merge.merge-extension' => ['tabs' => ['main' => 'idea-to-paper-merge', 'strang_merge_index' => 'idea-to-paper-merge-extension'], 'label' => 'Strang Merge → Extension', 'components' => ['strang.merge-left', 'strang.merge-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.merge.merge-extension'],
        'strang.merge.merge-aggregated' => ['tabs' => ['main' => 'idea-to-paper-merge', 'strang_merge_index' => 'idea-to-paper-merge-aggregated'], 'label' => 'Strang Merge → Aggregated', 'components' => ['strang.merge-left', 'strang.merge-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.merge.merge-aggregated'],
        'strang.branch.branch-default' => ['tabs' => ['main' => 'idea-to-paper-branch', 'strang_branch_index' => 'branch-default'], 'label' => 'Strang Branch → Default', 'components' => ['strang.branch-left', 'strang.branch-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.branch.branch-default'],
        'strang.branch.branch-offset' => ['tabs' => ['main' => 'idea-to-paper-branch', 'strang_branch_index' => 'branch-offset'], 'label' => 'Strang Branch → Offset', 'components' => ['strang.branch-left', 'strang.branch-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.branch.branch-offset'],
        'strang.branch.branch-step' => ['tabs' => ['main' => 'idea-to-paper-branch', 'strang_branch_index' => 'branch-step'], 'label' => 'Strang Branch → Step', 'components' => ['strang.branch-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.branch.branch-step'],
        'strang.branch.branch-continuation' => ['tabs' => ['main' => 'idea-to-paper-branch', 'strang_branch_index' => 'branch-continuation'], 'label' => 'Strang Branch → Continuation', 'components' => ['strang.branch-left', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.branch.branch-continuation'],
        'strang.branch.branch-return' => ['tabs' => ['main' => 'idea-to-paper-branch', 'strang_branch_index' => 'branch-return'], 'label' => 'Strang Branch → Return', 'components' => ['strang.branch-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.branch.branch-return'],
        'strang.branch.branch-mismatch' => ['tabs' => ['main' => 'idea-to-paper-branch', 'strang_branch_index' => 'branch-mismatch'], 'label' => 'Strang Branch → Mismatch', 'components' => ['strang.branch-left', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.branch.branch-mismatch'],
        'strang.rekey.rekey-default' => ['tabs' => ['main' => 'idea-to-paper-rekey', 'strang_rekey_index' => 'rekey-default'], 'label' => 'Strang Rekey → Default', 'components' => ['strang.rekey-source-left', 'strang.rekey-target-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.rekey.rekey-default'],
        'strang.rekey.rekey-source' => ['tabs' => ['main' => 'idea-to-paper-rekey', 'strang_rekey_index' => 'rekey-source'], 'label' => 'Strang Rekey → Source', 'components' => ['strang.rekey-source-left', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.rekey.rekey-source'],
        'strang.rekey.rekey-target' => ['tabs' => ['main' => 'idea-to-paper-rekey', 'strang_rekey_index' => 'rekey-target'], 'label' => 'Strang Rekey → Target', 'components' => ['strang.rekey-target-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.rekey.rekey-target'],
        'strang.rekey.rekey-compressed' => ['tabs' => ['main' => 'idea-to-paper-rekey', 'strang_rekey_index' => 'rekey-compressed'], 'label' => 'Strang Rekey → Compressed', 'components' => ['strang.rekey-source-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.strang.rekey.rekey-compressed'],
        'flow.flow-start' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-start'], 'label' => 'Flow → Flow start', 'components' => ['strang.flow-start'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.flow-start'],
        'flow.flow-step' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-step'], 'label' => 'Flow → Flow step', 'components' => ['strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.flow-step'],
        'flow.flow-branch-steps' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-branch-steps'], 'label' => 'Flow → Flow branch steps', 'components' => ['strang.flow-if-else', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.flow-branch-steps'],
        'flow.if.flow-if-simple' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-simple'], 'label' => 'Flow → Flow IF → IF', 'components' => ['strang.flow-if', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-simple'],
        'flow.if.flow-if-else' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-else'], 'label' => 'Flow → Flow IF → IF ELSE', 'components' => ['strang.flow-if-else', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-else'],
        'flow.if.flow-if-elseif' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-elseif'], 'label' => 'Flow → Flow IF → IF ELSEIF', 'components' => ['strang.flow-if-elseif', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-elseif'],
        'flow.if.flow-if-elseif-multi' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-elseif-multi'], 'label' => 'Flow → Flow IF → IF ELSEIF multi', 'components' => ['strang.flow-if-elseif-multi', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-elseif-multi'],
        'flow.if.flow-if-ternary' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-ternary'], 'label' => 'Flow → Flow IF → IF ternär', 'components' => ['strang.flow-if-ternary', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-ternary'],
        'flow.if.flow-if-nested-1' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-1'], 'label' => 'Flow → Flow IF → IF nested 1', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-1'],
        'flow.if.flow-if-nested-2' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-2'], 'label' => 'Flow → Flow IF → IF nested 2', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-2'],
        'flow.if.flow-if-nested-3' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-3'], 'label' => 'Flow → Flow IF → IF nested 3', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-3'],
        'flow.if.flow-if-nested-4' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-4'], 'label' => 'Flow → Flow IF → IF nested 4', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-4'],
        'flow.if.flow-if-nested-5' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-5'], 'label' => 'Flow → Flow IF → IF nested 5', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-5'],
        'flow.if.flow-if-nested-6' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-6'], 'label' => 'Flow → Flow IF → IF nested 6', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-6'],
        'flow.if.flow-if-nested-7' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-7'], 'label' => 'Flow → Flow IF → IF nested 7', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-7'],
        'flow.if.flow-if-nested-8' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-8'], 'label' => 'Flow → Flow IF → IF nested 8', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-8'],
        'flow.if.flow-if-nested-9' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-if', 'flow_flow_if' => 'flow-if-nested-9'], 'label' => 'Flow → Flow IF → IF nested 9', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-if-elseif-multi', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.if.flow-if-nested-9'],
        'flow.switch-case.flow-switch-case-default' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-default'], 'label' => 'Flow → Flow SWITCH/CASE → CASEs single', 'components' => ['strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-default'],
        'flow.switch-case.flow-switch-case-grouped' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-grouped'], 'label' => 'Flow → Flow SWITCH/CASE → CASEs grouped', 'components' => ['strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-grouped'],
        'flow.switch-case.flow-switch-case-grouped-3' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-grouped-3'], 'label' => 'Flow → Flow SWITCH/CASE → CASE grouped (3)', 'components' => ['strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-grouped-3'],
        'flow.switch-case.flow-switch-case-grouped-multi' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-grouped-multi'], 'label' => 'Flow → Flow SWITCH/CASE → CASE grouped (>4)', 'components' => ['strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-grouped-multi'],
        'flow.switch-case.flow-switch-case-nested' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-nested'], 'label' => 'Flow → Flow SWITCH/CASE → CASE nested', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-nested'],
        'flow.switch-case.flow-switch-case-without-default' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-without-default'], 'label' => 'Flow → Flow SWITCH/CASE → CASEs without DEFAULT', 'components' => ['strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-without-default'],
        'flow.switch-case.flow-switch-case-fallthrough' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-fallthrough'], 'label' => 'Flow → Flow SWITCH/CASE → CASE fallthrough', 'components' => ['strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-fallthrough'],
        'flow.switch-case.flow-switch-case-nested-1' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-nested-1'], 'label' => 'Flow → Flow SWITCH/CASE → CASE SWITCH CASE (1)', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-nested-1'],
        'flow.switch-case.flow-switch-case-nested-2' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-nested-2'], 'label' => 'Flow → Flow SWITCH/CASE → CASE SWITCH CASE (2)', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-nested-2'],
        'flow.switch-case.flow-switch-case-two-nested-1' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-two-nested-1'], 'label' => 'Flow → Flow SWITCH/CASE → 2 nested CASEs in SWITCH (1)', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-two-nested-1'],
        'flow.switch-case.flow-switch-case-two-nested-2' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-two-nested-2'], 'label' => 'Flow → Flow SWITCH/CASE → 2 nested CASEs in SWITCH (2)', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-two-nested-2'],
        'flow.switch-case.flow-switch-case-two-nested-3' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-two-nested-3'], 'label' => 'Flow → Flow SWITCH/CASE → 2 nested CASEs in SWITCH (3)', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-two-nested-3'],
        'flow.switch-case.flow-switch-case-action-sequence' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-action-sequence'], 'label' => 'Flow → Flow SWITCH/CASE → Action → Nested → Action', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-action-sequence'],
        // Retained test page; not an active navigation destination.
        // 'flow.switch-case.flow-switch-case-test' => ['tabs' => ['main' => 'idea-to-paper-flow', 'flow_index' => 'flow-switch-case', 'flow_switch_case' => 'flow-switch-case-test'], 'label' => 'Flow → Flow SWITCH/CASE → SWITCH/CASE Test', 'components' => ['parts.sideways', 'parts.start', 'strang.flow-start', 'strang.flow-step', 'strang.flow-switch-case'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.flow.switch-case.flow-switch-case-test'],
        '00-graph-final' => ['tabs' => ['results' => 'idea-to-paper-draft'], 'label' => 'Thought draft', 'components' => ['strang.branch-end', 'strang.branch-right', 'strang.merge-left', 'strang.rekey-source-left', 'strang.rekey-target-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper.00-graph-final'],
        '_graph-current-result' => ['tabs' => ['results' => 'idea-to-paper-result'], 'label' => 'Current result', 'components' => ['strang.branch-right', 'strang.merge-left', 'strang.rekey-source-left', 'strang.rekey-target-right', 'strang.trunk'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper._graph-current-result'],
        '_graph-flow-diagram' => ['tabs' => ['results' => 'idea-to-paper-flow-result'], 'label' => 'Flow diagram', 'components' => ['strang.flow-if-else', 'strang.flow-start', 'strang.flow-step'], 'view' => 'translation-workbench::pages.tw-graph.samples.documentation.idea-to-paper._graph-flow-diagram'],
    ];

    public static function reference(string $component): ?array
    {
        if (! in_array($component, self::COMPONENTS, true)) {
            return null;
        }
        [$layer, $name] = explode('.', $component, 2);

        return [
            'main' => 'idea-to-paper-props-and-connections',
            'reference_index' => 'reference-'.$layer,
            'reference_'.$layer => 'reference-'.($layer === 'parts' ? 'parts-' : '').$name,
        ];
    }

    public static function examples(string $component): array
    {
        return array_filter(self::EXAMPLES, fn ($example) => in_array($component, $example['components'], true));
    }

    public static function url(array $tabs, string $fragment = 'tw-graph-documentation'): string
    {
        // Livewire updates are POSTed to /livewire/update; links must keep the page URL.
        return Livewire::originalUrl().'?'.http_build_query(['graph-tabs' => $tabs]).'#'.$fragment;
    }
}
