{{-- packages/gunreip/laravel-translation-workbench/resources/views/livewire/entries/findings/code-update-plan.blade.php --}}

@php
    $report = $codeUpdatePlanReport ?? null;
    $summary = $report['summary'] ?? [];
    $filteredSummary = $report['filtered_summary'] ?? [];
    $updatesByState = $report['updates_by_state'] ?? [];
    $filters = $report['filters'] ?? ['state' => 'all', 'search' => '', 'active' => false];
    $applyReport = $codeUpdateApplyReport ?? null;
    $applySummary = $applyReport['summary'] ?? [];
    $applyDiff = $applyReport['diff'] ?? [];
    $applyResultsByState = $applyReport['results_by_state'] ?? [];
    $applyReady =
        ($summary['safe_updates'] ?? 0) > 0 &&
        ($summary['missing_lang_values'] ?? 0) === 0 &&
        ($summary['stale_source'] ?? 0) === 0 &&
        ($summary['unsupported_expression'] ?? 0) === 0 &&
        ($summary['missing_source_file'] ?? 0) === 0;
    $visibleStates =
        ($filters['state'] ?? 'all') === 'all'
            ? ['safe_update', 'missing_lang_values', 'manual_review', 'stale_source', 'already_current']
            : [(string) $filters['state']];

    $stateMeta = [
        'safe_update' => [
            'title' => __('Safe updates'),
            'color' => 'green',
            'icon' => 'circle-check',
            'text' => __(
                'Reviewed static translation calls where the first literal argument can be replaced with the final translation key.',
            ),
        ],
        'manual_review' => [
            'title' => __('Manual review'),
            'color' => 'amber',
            'icon' => 'triangle-alert',
            'text' => __(
                'Dynamic or more complex expressions that need a dedicated workflow before source code can be changed.',
            ),
        ],
        'missing_lang_values' => [
            'title' => __('Missing lang values'),
            'color' => 'red',
            'icon' => 'languages',
            'text' => __(
                'Reviewed keys where the source or target translation value is missing. These rows must not be written to source code before the lang/* values exist.',
            ),
        ],
        'stale_source' => [
            'title' => __('ui.source.stale-source'),
            'color' => 'red',
            'icon' => 'file-exclamation-point',
            'text' => __(
                'The recorded raw expression was not found in the current source file anymore. Run a fresh scan or review manually.',
            ),
        ],
        'already_current' => [
            'title' => __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.already_current'),
            'color' => 'sky',
            'icon' => 'check-check',
            'text' => __('The current code already uses the reviewed translation key.'),
        ],
    ];
@endphp

<div class="mt-4 space-y-4">
    @if (!$report)
        <flux:callout
            color="amber"
            icon="file-exclamation-point"
        >
            <flux:callout.heading>{{ __('No code update plan found') }}</flux:callout.heading>
            <flux:callout.text>
                {{ __('Run php artisan translation-workbench:plan-code-updates to generate a report before reviewing planned code changes here.') }}
            </flux:callout.text>
        </flux:callout>
    @else
        <flux:callout
            color="sky"
            icon="scan-search"
        >
            <flux:callout.heading>
                <span class="inline-flex flex-wrap items-center gap-2">
                    <span>{{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.code_update_plan') }}</span>
                    <flux:badge
                        size="sm"
                        color="sky"
                    >
                        {{ __('Report only') }}
                    </flux:badge>
                </span>
            </flux:callout.heading>
            <flux:callout.text>
                {{ __('Latest reviewed code update plan generated by :command.', ['command' => $report['command']]) }}
                @if ($report['generated_at'])
                    <span class="ml-1">
                        <x-ui.date-time.date :value="$report['generated_at']" />
                        <x-ui.date-time.time :value="$report['generated_at']" />
                    </span>
                @endif
            </flux:callout.text>
        </flux:callout>

        <div class="grid grid-cols-1 gap-3 xl:grid-cols-4">
            <flux:callout
                class="xl:col-span-3"
                color="{{ $applyReady ? 'green' : 'amber' }}"
                icon="{{ $applyReady ? 'circle-check' : 'triangle-alert' }}"
            >
                <flux:callout.heading>
                    {{ $applyReady ? __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.apply_ready_plan') : __('Plan needs review') }}
                </flux:callout.heading>
                <flux:callout.text>
                    {{ $applyReady
                        ? __('The plan contains safe updates and no stale, missing-file or unsupported rows.')
                        : __('Review missing lang values, stale, missing-file or unsupported rows before applying code updates.') }}
                </flux:callout.text>
            </flux:callout>

            <flux:callout
                color="{{ $filters['active'] ?? false ? 'cyan' : 'zinc' }}"
                icon="sliders-horizontal"
            >
                <flux:callout.heading>{{ __('Filtered rows') }}</flux:callout.heading>
                <flux:callout.text>
                    <span class="text-lg font-semibold tabular-nums">
                        {{ number_format((int) ($filteredSummary['rows'] ?? 0)) }}
                    </span>
                </flux:callout.text>
            </flux:callout>
        </div>

        <flux:callout
            color="zinc"
            icon="terminal"
        >
            <flux:callout.heading>{{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.controlled_write_workflow') }}</flux:callout.heading>
            <flux:callout.text>
                {{ __('This screen only reviews plans and refreshes dry-run patch reports. Source files are changed intentionally through php artisan translation-workbench:apply-code-updates --write.') }}
            </flux:callout.text>
        </flux:callout>

        <div class="grid grid-cols-1 gap-3 xl:grid-cols-4">
            @foreach ([['title' => __('Reviewed findings'), 'count' => $summary['reviewed_findings'] ?? 0, 'color' => 'sky', 'icon' => 'scan-search'], ['title' => __('Safe updates'), 'count' => $summary['safe_updates'] ?? 0, 'color' => 'green', 'icon' => 'circle-check'], ['title' => __('Missing lang values'), 'count' => $summary['missing_lang_values'] ?? 0, 'color' => ($summary['missing_lang_values'] ?? 0) > 0 ? 'red' : 'green', 'icon' => 'languages'], ['title' => __('Manual review'), 'count' => $summary['manual_review'] ?? 0, 'color' => ($summary['manual_review'] ?? 0) > 0 ? 'amber' : 'green', 'icon' => 'triangle-alert']] as $callout)
                <flux:callout
                    color="{{ $callout['color'] }}"
                    icon="{{ $callout['icon'] }}"
                >
                    <flux:callout.heading>{{ $callout['title'] }}</flux:callout.heading>
                    <flux:callout.text>
                        <span class="text-lg font-semibold tabular-nums">
                            {{ number_format((int) $callout['count']) }}
                        </span>
                    </flux:callout.text>
                </flux:callout>
            @endforeach
        </div>

        <flux:callout
            color="{{ $applyReport ? 'cyan' : 'zinc' }}"
            icon="file-diff"
        >
            <flux:callout.heading>
                <span class="flex flex-wrap items-center justify-between gap-2">
                    <span class="inline-flex flex-wrap items-center gap-2">
                        <span>{{ __('Patch preview') }}</span>
                        @if ($applyReport)
                            <flux:badge
                                size="sm"
                                color="{{ $applyReport['write'] ? 'green' : 'sky' }}"
                            >
                                {{ $applyReport['write'] ? __('ui.label.written') : __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.dry_run') }}
                            </flux:badge>
                            <flux:badge size="sm">
                                {{ __('Files') }}: {{ number_format((int) ($applySummary['diff_files'] ?? 0)) }}
                            </flux:badge>
                            <flux:badge size="sm">
                                {{ __('Lines') }}: {{ number_format((int) ($applyDiff['line_count'] ?? 0)) }}
                            </flux:badge>
                        @endif
                    </span>

                    <x-ui.tooltip.simple
                        :title="__('Refresh dry-run patch')"
                        :text="__('Regenerates the apply report and patch preview without changing source files.')"
                    >
                        <flux:button
                            type="button"
                            size="xs"
                            variant="subtle"
                            icon="refresh-cw"
                            wire:click="refreshCodeUpdateApplyReport"
                            wire:loading.attr="disabled"
                            wire:target="refreshCodeUpdateApplyReport"
                        >
                            {{ __('Refresh dry-run') }}
                        </flux:button>
                    </x-ui.tooltip.simple>
                </span>
            </flux:callout.heading>
            <flux:callout.text>
                @if ($applyReport)
                    <div class="space-y-3">
                        <div class="wrap-anywhere font-mono text-xs text-zinc-500 dark:text-zinc-400">
                            {{ $applyReport['diff_path'] }}
                        </div>

                        <div class="flex flex-wrap gap-2">
                            <flux:badge size="sm">{{ __('ui.label.would-apply') }}:
                                {{ number_format((int) ($applySummary['would_apply'] ?? 0)) }}</flux:badge>
                            <flux:badge size="sm">{{ __('ui.apply.applied') }}:
                                {{ number_format((int) ($applySummary['applied'] ?? 0)) }}</flux:badge>
                            <flux:badge
                                size="sm"
                                color="{{ ($applySummary['duplicate_expression'] ?? 0) > 0 ? 'amber' : 'green' }}"
                            >
                                {{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.duplicates') }}:
                                {{ number_format((int) ($applySummary['duplicate_expression'] ?? 0)) }}
                            </flux:badge>
                            <flux:badge
                                size="sm"
                                color="{{ ($applySummary['duplicate_reviewed'] ?? 0) > 0 ? 'cyan' : 'zinc' }}"
                            >
                                {{ __('Reviewed duplicates') }}:
                                {{ number_format((int) ($applySummary['duplicate_reviewed'] ?? 0)) }}
                            </flux:badge>
                        </div>

                        @if ($applyDiff['preview'] ?? '')
                            <pre
                                class="max-h-96 overflow-auto rounded-md border border-zinc-200 bg-zinc-950 p-3 text-xs text-zinc-100 dark:border-zinc-700"><code>{{ $applyDiff['preview'] }}</code></pre>

                            @if ($applyDiff['truncated'] ?? false)
                                <flux:text class="text-xs text-zinc-500">
                                    {{ __('Preview truncated. Open the patch file for the full diff.') }}
                                </flux:text>
                            @endif
                        @else
                            <flux:text class="text-sm text-zinc-500">
                                {{ __('No patch content available. Run php artisan translation-workbench:apply-code-updates to generate a dry-run patch.') }}
                            </flux:text>
                        @endif
                    </div>
                @else
                    {{ __('Run php artisan translation-workbench:apply-code-updates to generate a dry-run patch report before applying source code changes.') }}
                @endif
            </flux:callout.text>
        </flux:callout>

        @if ($applyReport)
            <flux:callout
                variant="danger"
                icon="triangle-alert"
            >
                <flux:callout.heading>{{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.apply_result_freshness') }}</flux:callout.heading>
                <flux:callout.text>
                    <div class="flex flex-wrap items-center gap-2">
                        <span>
                            {{ __('Expectation and result do not match? Refresh the dry-run report or run php artisan translation-workbench:apply-code-updates.') }}
                        </span>

                        @if ($applyReport['generated_at'] ?? null)
                            <flux:badge size="sm">
                                <span class="mr-2 text-sm">{{ __('Last dry-run') }}:</span>
                                <x-ui.date-time.date :value="$applyReport['generated_at']" />
                                <x-ui.date-time.time :value="$applyReport['generated_at']" />
                            </flux:badge>
                            <flux:badge
                                size="sm"
                                color="red"
                            >
                                <x-ui.date-time.ago :value="$applyReport['generated_at']" />
                            </flux:badge>
                        @endif
                    </div>
                </flux:callout.text>
            </flux:callout>

            @php
                $applyStateMeta = [
                    'would_apply' => ['title' => __('ui.label.would-apply'), 'color' => 'green', 'icon' => 'circle-check'],
                    'duplicate_expression' => [
                        'title' => __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.duplicate_expressions'),
                        'color' => 'amber',
                        'icon' => 'copy-x',
                    ],
                    'duplicate_reviewed' => [
                        'title' => __('Reviewed duplicates'),
                        'color' => 'cyan',
                        'icon' => 'badge-check',
                    ],
                    'stale_source' => [
                        'title' => __('ui.source.stale-source'),
                        'color' => 'red',
                        'icon' => 'file-exclamation-point',
                    ],
                ];
            @endphp

            <flux:callout
                color="zinc"
                icon="list-checks"
            >
                <flux:callout.heading>{{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.apply_results') }}</flux:callout.heading>
                <flux:callout.text>
                    {{ __('Dry-run apply results grouped by the concrete action state. Only one result table is shown at a time.') }}
                </flux:callout.text>

                <div class="mt-3 max-w-full overflow-hidden">
                    <flux:tab.group>
                        <flux:tabs>
                            @foreach ($applyStateMeta as $state => $meta)
                                @php
                                    $rows = collect($applyResultsByState[$state] ?? []);
                                @endphp

                                <flux:tab name="code-update-apply-{{ $state }}">
                                    <span class="inline-flex items-center gap-2">
                                        @if ($state === 'would_apply')
                                            <flux:icon.circle-check class="size-4" />
                                        @elseif ($state === 'duplicate_expression')
                                            <flux:icon.copy-x class="size-4" />
                                        @elseif ($state === 'duplicate_reviewed')
                                            <flux:icon.badge-check class="size-4" />
                                        @else
                                            <flux:icon.file-exclamation-point class="size-4" />
                                        @endif
                                        <span>{{ $meta['title'] }}</span>
                                        <flux:badge
                                            size="sm"
                                            color="{{ $meta['color'] }}"
                                        >
                                            {{ number_format($rows->count()) }}
                                        </flux:badge>
                                    </span>
                                </flux:tab>
                            @endforeach
                        </flux:tabs>

                        @foreach ($applyStateMeta as $state => $meta)
                            @php
                                $rows = collect($applyResultsByState[$state] ?? []);
                            @endphp

                            <flux:tab.panel name="code-update-apply-{{ $state }}">
                                <div
                                    class="mt-3 max-h-96 max-w-full overflow-auto rounded-md border border-zinc-200 dark:border-zinc-700">
                                    <flux:table
                                        class="min-w-[56rem] table-fixed"
                                        container:class="max-h-96 max-w-full overflow-auto"
                                    >
                                        <flux:table.columns
                                            class="bg-white dark:bg-zinc-800"
                                            sticky
                                        >
                                            <flux:table.column class="w-24">{{ __('ID') }}</flux:table.column>
                                            <flux:table.column>{{ __('ui.source.source') }}</flux:table.column>
                                            <flux:table.column class="w-36">{{ __('ui.state.state') }}</flux:table.column>
                                            <flux:table.column
                                                class="w-28"
                                                align="center"
                                            >
                                                {{ __('ui.table.headers.actions') }}
                                            </flux:table.column>
                                        </flux:table.columns>
                                        <flux:table.rows>
                                            @forelse ($rows as $row)
                                                @php
                                                    $sourceAbsolutePath = str_replace(
                                                        '\\',
                                                        '/',
                                                        base_path($row['source_path']),
                                                    );
                                                    $sourceEditorPath = str_replace(
                                                        '%2F',
                                                        '/',
                                                        rawurlencode($sourceAbsolutePath),
                                                    );
                                                    $sourceEditorLine = $row['source_line']
                                                        ? ':' . $row['source_line']
                                                        : '';
                                                    $sourceEditorUrl =
                                                        'vscode://vscode-remote/wsl+' .
                                                        rawurlencode(
                                                            (string) config(
                                                                'translation-workbench.editor.vscode_wsl_distro',
                                                            ),
                                                        ) .
                                                        $sourceEditorPath .
                                                        $sourceEditorLine;
                                                @endphp
                                                <flux:table.row>
                                                    <flux:table.cell>
                                                        <div class="flex flex-wrap gap-1 tabular-nums">
                                                            <flux:badge size="sm">F#{{ $row['finding_id'] }}
                                                            </flux:badge>
                                                            <flux:badge size="sm">K#{{ $row['key_id'] }}
                                                            </flux:badge>
                                                        </div>
                                                    </flux:table.cell>
                                                    <flux:table.cell>
                                                        <div class="wrap-anywhere font-mono text-xs">
                                                            {{ $row['source_path'] }}@if ($row['source_line'])
                                                                :{{ $row['source_line'] }}
                                                            @endif
                                                        </div>
                                                        <div
                                                            class="wrap-anywhere mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                                                            {{ $row['reason'] }}
                                                        </div>
                                                    </flux:table.cell>
                                                    <flux:table.cell>
                                                        @if (($row['occurrences'] ?? null) !== null)
                                                            <div class="flex flex-col items-start gap-1">
                                                                <flux:badge
                                                                    size="sm"
                                                                    color="{{ $state === 'duplicate_reviewed' ? 'cyan' : 'amber' }}"
                                                                >
                                                                    {{ __('Occurrences') }}: {{ $row['occurrences'] }}
                                                                </flux:badge>

                                                                @if (($row['conflict_review'] ?? null) || $state === 'duplicate_reviewed')
                                                                    <flux:badge
                                                                        size="sm"
                                                                        color="cyan"
                                                                    >
                                                                        {{ __('Reviewed') }}:
                                                                        {{ $row['conflict_review']['label'] ?? __('ui.filters.yes') }}
                                                                    </flux:badge>

                                                                    @if (($row['conflict_review']['decision'] ?? null) === 'duplicate_dynamic_manual_workflow')
                                                                        <x-ui.tooltip.simple
                                                                            :title="__('Dynamic/manual workflow')"
                                                                            :text="__(
                                                                                'This reviewed duplicate is intentionally excluded from the normal code apply workflow and must be handled by the dynamic translation workflow.',
                                                                            )"
                                                                        >
                                                                            <flux:badge
                                                                                size="sm"
                                                                                color="purple"
                                                                            >
                                                                                {{ __('Dynamic/manual') }}
                                                                            </flux:badge>
                                                                        </x-ui.tooltip.simple>
                                                                    @endif
                                                                @else
                                                                    <flux:badge
                                                                        size="sm"
                                                                        color="red"
                                                                    >
                                                                        {{ __('Review needed') }}
                                                                    </flux:badge>
                                                                @endif
                                                            </div>
                                                        @else
                                                            <div class="flex flex-col items-start gap-1">
                                                                <flux:badge
                                                                    size="sm"
                                                                    color="{{ $meta['color'] }}"
                                                                >
                                                                    {{ $row['state'] }}
                                                                </flux:badge>

                                                                @if ($row['conflict_review'] ?? null)
                                                                    <flux:badge
                                                                        size="sm"
                                                                        color="cyan"
                                                                    >
                                                                        {{ __('Reviewed conflict') }}:
                                                                        {{ $row['conflict_review']['label'] }}
                                                                    </flux:badge>
                                                                @endif
                                                            </div>
                                                        @endif
                                                    </flux:table.cell>
                                                    <flux:table.cell>
                                                        <div class="flex items-center justify-center gap-1">
                                                            <x-ui.tooltip.simple
                                                                :title="__('Open source in VS Code')"
                                                                :text="__(
                                                                    'Opens the current source file at the recorded line, assuming the source has not moved since the last apply dry-run.',
                                                                )"
                                                            >
                                                                <flux:button
                                                                    class="h-6 w-6"
                                                                    type="button"
                                                                    size="xs"
                                                                    variant="ghost"
                                                                    icon="external-link"
                                                                    icon:class="text-sky-500 dark:text-sky-400"
                                                                    :href="$sourceEditorUrl"
                                                                    :aria-label="__('Open source in VS Code')"
                                                                />
                                                            </x-ui.tooltip.simple>

                                                            @if (in_array($state, ['duplicate_expression', 'duplicate_reviewed'], true))
                                                                <x-ui.tooltip.simple
                                                                    :title="__('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.review_duplicate_expression')"
                                                                    :text="__(
                                                                        'Stores how this duplicate expression should be handled before code updates are applied.',
                                                                    )"
                                                                >
                                                                    <flux:button
                                                                        class="h-6 w-6"
                                                                        type="button"
                                                                        size="xs"
                                                                        variant="ghost"
                                                                        icon="badge-check"
                                                                        icon:class="text-amber-500 dark:text-amber-400"
                                                                        wire:click="openCodeUpdateConflictReview({{ $row['finding_id'] }}, {{ $row['key_id'] }})"
                                                                        :aria-label="__('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.review_duplicate_expression')"
                                                                    />
                                                                </x-ui.tooltip.simple>
                                                            @endif

                                                            @if ($state === 'manual_review')
                                                                <x-ui.tooltip.simple
                                                                    :title="__('Review dynamic data')"
                                                                    :text="__(
                                                                        'Opens the dynamic data review workflow for this manual review row.',
                                                                    )"
                                                                >
                                                                    <flux:button
                                                                        class="h-6 w-6"
                                                                        type="button"
                                                                        size="xs"
                                                                        variant="ghost"
                                                                        icon="database-zap"
                                                                        icon:class="text-violet-500 dark:text-violet-400"
                                                                        wire:click="openDynamicReviewModal({{ $row['finding_id'] }})"
                                                                        :aria-label="__('Review dynamic data')"
                                                                    />
                                                                </x-ui.tooltip.simple>
                                                            @endif

                                                            <x-ui.tooltip.simple
                                                                :title="__('Open finding review')"
                                                                :text="__(
                                                                    'Opens the review modal for this concrete finding.',
                                                                )"
                                                            >
                                                                <flux:button
                                                                    class="h-6 w-6"
                                                                    type="button"
                                                                    size="xs"
                                                                    variant="ghost"
                                                                    icon="scan-search"
                                                                    icon:class="text-cyan-500 dark:text-cyan-400"
                                                                    wire:click="openReviewModal({{ $row['finding_id'] }})"
                                                                    :aria-label="__('Open finding review')"
                                                                />
                                                            </x-ui.tooltip.simple>
                                                        </div>
                                                    </flux:table.cell>
                                                </flux:table.row>
                                                @empty
                                                    <flux:table.row>
                                                        <flux:table.cell
                                                            colspan="4"
                                                            align="center"
                                                        >
                                                            <flux:text class="text-sm text-zinc-500">
                                                                {{ __('No rows.') }}
                                                            </flux:text>
                                                        </flux:table.cell>
                                                    </flux:table.row>
                                                @endforelse
                                            </flux:table.rows>
                                        </flux:table>
                                    </div>
                                </flux:tab.panel>
                            @endforeach
                        </flux:tab.group>
                    </div>
                </flux:callout>
            @endif

            <div class="grid grid-cols-1 items-end gap-3 xl:grid-cols-6">
                <flux:field class="xl:col-span-3">
                    <flux:label>{{ __('Search code update plan') }}</flux:label>
                    <flux:input.group>
                        <flux:input.group.prefix>
                            <flux:icon.search />
                        </flux:input.group.prefix>
                        <flux:input
                            type="search"
                            icon="search"
                            clearable
                            copyable
                            :placeholder="__('Source, expression, translation key or reason')"
                            wire:model.live.debounce.300ms="codeUpdatePlanSearch"
                        />
                    </flux:input.group>
                </flux:field>

                <flux:field class="xl:col-span-2">
                    <flux:label>{{ __('Plan state') }}</flux:label>
                    <flux:input.group>
                        <flux:input.group.prefix>
                            <flux:icon.sliders-horizontal />
                        </flux:input.group.prefix>
                        <flux:select
                            variant="listbox"
                            searchable
                            wire:model.live="codeUpdatePlanState"
                        >
                            <flux:select.option value="all">{{ __('ui.states.all-states') }}</flux:select.option>
                            <flux:select.option value="safe_update">{{ __('Safe updates') }}</flux:select.option>
                            <flux:select.option value="missing_lang_values">{{ __('Missing lang values') }}</flux:select.option>
                            <flux:select.option value="manual_review">{{ __('Manual review') }}</flux:select.option>
                            <flux:select.option value="stale_source">{{ __('ui.source.stale-source') }}</flux:select.option>
                            <flux:select.option value="already_current">{{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.already_current') }}</flux:select.option>
                            <flux:select.option value="unsupported_expression">{{ __('Unsupported expression') }}
                            </flux:select.option>
                            <flux:select.option value="missing_source_file">{{ __('Missing source file') }}
                            </flux:select.option>
                        </flux:select>
                    </flux:input.group>
                </flux:field>

                <div class="flex justify-end xl:col-span-1">
                    <x-ui.button.reset wire:click="resetCodeUpdatePlanFilters" />
                </div>
            </div>

            @foreach ($visibleStates as $state)
                @php
                    if (!isset($stateMeta[$state])) {
                        continue;
                    }

                    $rows = collect($updatesByState[$state] ?? []);
                    $meta = $stateMeta[$state];
                @endphp

                <flux:callout
                    color="{{ $meta['color'] }}"
                    icon="{{ $meta['icon'] }}"
                >
                    <flux:callout.heading>
                        <span class="inline-flex flex-wrap items-center gap-2">
                            <span>{{ $meta['title'] }}</span>
                            <flux:badge size="sm">{{ __('Rows') }}: {{ number_format($rows->count()) }}
                            </flux:badge>
                        </span>
                    </flux:callout.heading>
                    <flux:callout.text>{{ $meta['text'] }}</flux:callout.text>

                    <div class="mt-3 max-w-full overflow-hidden rounded-md border border-zinc-200 dark:border-zinc-700">
                        <div class="max-h-96 max-w-full overflow-auto">
                            <flux:table
                                class="min-w-[72rem] table-fixed"
                                container:class="max-h-96 max-w-full overflow-auto"
                            >
                                <flux:table.columns
                                    class="bg-white dark:bg-zinc-800"
                                    sticky
                                >
                                    {{-- <flux:table.column class="w-20">{{ __('ID') }}</flux:table.column> --}}
                                    <flux:table.column
                                        class="w-20 text-xs text-zinc-500 dark:text-zinc-200"
                                        align="center"
                                    >
                                        <flux:icon.hash
                                            class="size-4"
                                            stroke-width="1"
                                        />
                                        <x-ui.tooltip.simple
                                            :title="__('Finding ID and Key ID')"
                                            :texts="[
                                                'F#' => __(
                                                    'Finding ID: the concrete code finding, including source file, line and raw expression.',
                                                ),
                                                'K#' => __(
                                                    'Key ID: the reviewed Translation Workbench key linked to that finding and used for the planned replacement.',
                                                ),
                                            ]"
                                        />
                                    </flux:table.column>
                                    <flux:table.column class="">{{ __('ui.source.source') }}</flux:table.column>
                                    <flux:table.column class="">{{ __('packages.gunreip.laravel_translation_workbench.resources.views.livewire.entries.findings.code_update_plan.current_expression') }}</flux:table.column>
                                    <flux:table.column class="">
                                        {{ $state === 'safe_update' || $state === 'already_current' ? __('Planned expression') : __('Reason') }}
                                    </flux:table.column>
                                    <flux:table.column
                                        class="w-20"
                                        align="center"
                                    >
                                        {{ __('ui.table.headers.actions') }}
                                    </flux:table.column>
                                </flux:table.columns>
                                <flux:table.rows>
                                    @forelse ($rows as $row)
                                        @php
                                            $sourceAbsolutePath = str_replace(
                                                '\\',
                                                '/',
                                                base_path($row['source_path']),
                                            );
                                            $sourceEditorPath = str_replace(
                                                '%2F',
                                                '/',
                                                rawurlencode($sourceAbsolutePath),
                                            );
                                            $sourceEditorLine = $row['source_line'] ? ':' . $row['source_line'] : '';
                                            $sourceEditorUrl =
                                                'vscode://vscode-remote/wsl+' .
                                                rawurlencode(
                                                    (string) config('translation-workbench.editor.vscode_wsl_distro'),
                                                ) .
                                                $sourceEditorPath .
                                                $sourceEditorLine;
                                        @endphp
                                        <flux:table.row>
                                            <flux:table.cell>
                                                <div class="flex flex-wrap justify-center gap-1 tabular-nums">
                                                    <flux:badge
                                                        color="lime"
                                                        size="sm"
                                                    >F#{{ $row['finding_id'] }}</flux:badge>
                                                    <flux:badge
                                                        color="fuchsia"
                                                        size="sm"
                                                    >K#{{ $row['key_id'] }}</flux:badge>
                                                </div>
                                            </flux:table.cell>
                                            <flux:table.cell>
                                                <div class="wrap-anywhere text-wrap font-mono text-xs">
                                                    {{ $row['source_path'] }}@if ($row['source_line'])
                                                        :{{ $row['source_line'] }}
                                                    @endif
                                                </div>
                                            </flux:table.cell>
                                            <flux:table.cell>
                                                <div class="wrap-anywhere text-wrap font-mono text-xs">
                                                    {{ $row['raw_expression'] }}</div>
                                            </flux:table.cell>
                                            <flux:table.cell>
                                                @if ($row['new_expression'])
                                                    <div
                                                        class="wrap-anywhere text-wrap font-mono text-xs text-green-700 dark:text-green-200">
                                                        {{ $row['new_expression'] }}
                                                    </div>
                                                @else
                                                    <div
                                                        class="wrap-anywhere text-wrap text-xs text-zinc-600 dark:text-zinc-300">
                                                        {{ $row['reason'] }}
                                                    </div>
                                                @endif
                                            </flux:table.cell>
                                            <flux:table.cell>
                                                <div class="flex items-center justify-center gap-1">
                                                    <x-ui.tooltip.simple
                                                        :title="__('Open source in VS Code')"
                                                        :text="__(
                                                            'Opens the current source file at the recorded line, assuming the source has not moved since the last plan run.',
                                                        )"
                                                    >
                                                        <flux:button
                                                            class="h-6 w-6"
                                                            type="button"
                                                            size="xs"
                                                            variant="ghost"
                                                            icon="external-link"
                                                            icon:class="text-sky-500 dark:text-sky-400"
                                                            :href="$sourceEditorUrl"
                                                            :aria-label="__('Open source in VS Code')"
                                                        />
                                                    </x-ui.tooltip.simple>

                                                    <x-ui.tooltip.simple
                                                        :title="__('Open finding review')"
                                                        :text="__(
                                                            'Opens the review modal for this concrete finding.',
                                                        )"
                                                    >
                                                        <flux:button
                                                            class="h-6 w-6"
                                                            type="button"
                                                            size="xs"
                                                            variant="ghost"
                                                            icon="scan-search"
                                                            icon:class="text-cyan-500 dark:text-cyan-400"
                                                            wire:click="openReviewModal({{ $row['finding_id'] }})"
                                                            :aria-label="__('Open finding review')"
                                                        />
                                                    </x-ui.tooltip.simple>
                                                </div>
                                            </flux:table.cell>
                                        </flux:table.row>
                                        @empty
                                            <flux:table.row>
                                                <flux:table.cell
                                                    colspan="5"
                                                    align="center"
                                                >
                                                    <flux:text class="text-sm text-zinc-500">
                                                        {{ __('No rows in this state.') }}
                                                    </flux:text>
                                                </flux:table.cell>
                                            </flux:table.row>
                                        @endforelse
                                    </flux:table.rows>
                                </flux:table>
                            </div>
                        </div>
                    </flux:callout>
                @endforeach
            @endif
        </div>
