{{-- packages/gunreip/laravel-translation-workbench/resources/views/livewire/entries/findings/export-report.blade.php --}}

@php
    $report = $langFileExportReport ?? null;
    $activeScope = is_array($report['active_scope'] ?? null) ? $report['active_scope'] : [];
    $missingKeys = collect($activeScope['target_main_missing_keys'] ?? []);
    $extraKeys = collect($activeScope['target_main_extra_keys'] ?? []);
    $valuesByLocale = collect($activeScope['values_by_locale'] ?? []);
    $conflicts = collect($report['conflicts'] ?? []);
@endphp

<div class="mt-4 space-y-4">
    @if (!$report)
        <flux:callout
            color="amber"
            icon="file-warning"
        >
            <flux:callout.heading>{{ __('No export report found') }}</flux:callout.heading>
            <flux:callout.text>
                {{ __('Run php artisan translation-workbench:export-lang-files to generate a dry-run report before reviewing export readiness here.') }}
            </flux:callout.text>
        </flux:callout>
    @else
        <flux:callout
            color="{{ $activeScope['target_main_balanced'] ? 'green' : 'amber' }}"
            icon="{{ $activeScope['target_main_balanced'] ? 'circle-check' : 'triangle-alert' }}"
        >
            <flux:callout.heading>
                <span class="inline-flex flex-wrap items-center gap-2">
                    <span>{{ __('Lang file export report') }}</span>
                    <flux:badge
                        class="mr-3"
                        size="sm"
                        color="{{ $report['dry_run'] ? 'sky' : 'green' }}"
                    >
                        {{ $report['dry_run'] ? __('Dry run') : __('ui.written') }}
                    </flux:badge>
                    <flux:badge
                        class="mr-3"
                        size="sm"
                        color="{{ $activeScope['target_main_balanced'] ? 'green' : 'amber' }}"
                    >
                        {{ $activeScope['target_main_balanced'] ? __('Balanced') : __('Not balanced') }}
                    </flux:badge>
                </span>
            </flux:callout.heading>
            <flux:callout.text>
                {{ __('Latest export readiness report generated by :command.', ['command' => $report['command']]) }}
                @if ($report['generated_at'])
                    <span class="ml-1">
                        <x-ui.date-time.date :value="$report['generated_at']" />
                        <x-ui.date-time.time :value="$report['generated_at']" />
                    </span>
                @endif
            </flux:callout.text>
        </flux:callout>

        <div class="grid grid-cols-1 gap-3 xl:grid-cols-5">
            @foreach ([['title' => __('Exportable values'), 'count' => $report['values_exportable'], 'color' => 'sky', 'icon' => 'database'], ['title' => __('New values'), 'count' => $report['values_new'], 'color' => $report['values_new'] > 0 ? 'cyan' : 'zinc', 'icon' => 'plus'], ['title' => __('Changed values'), 'count' => $report['values_changed'], 'color' => $report['values_changed'] > 0 ? 'amber' : 'zinc', 'icon' => 'pencil'], ['title' => __('Pruned values'), 'count' => $report['values_pruned'] ?? 0, 'color' => ($report['values_pruned'] ?? 0) > 0 ? 'amber' : 'zinc', 'icon' => 'scissors'], ['title' => __('Conflicts'), 'count' => $report['values_conflicted'], 'color' => $report['values_conflicted'] > 0 ? 'red' : 'green', 'icon' => $report['values_conflicted'] > 0 ? 'octagon-alert' : 'circle-check']] as $callout)
                <flux:callout
                    color="{{ $callout['color'] }}"
                    icon="{{ $callout['icon'] }}"
                >
                    <flux:callout.heading>{{ $callout['title'] }}</flux:callout.heading>
                    <flux:callout.text>
                        <span class="text-lg font-semibold tabular-nums">
                            {{ number_format((int) $callout['count']) }}
                        </span>
                    </flux:callout.text>
                </flux:callout>
            @endforeach
        </div>

        @if ($conflicts->isNotEmpty())
            <flux:callout
                color="red"
                icon="octagon-alert"
            >
                <flux:callout.heading>
                    <span class="inline-flex flex-wrap items-center gap-2">
                        <span>{{ __('Export conflicts') }}</span>
                        <flux:badge
                            size="sm"
                            color="red"
                        >
                            {{ number_format($conflicts->count()) }}
                        </flux:badge>
                    </span>
                </flux:callout.heading>
                <flux:callout.text>
                    {{ __('These values were skipped because their lang-key path conflicts with an existing scalar or nested value. Other exportable files and values are still written.') }}
                </flux:callout.text>

                <div class="mt-3 max-h-80 overflow-auto rounded-md border border-red-200 dark:border-red-700">
                    <flux:table container:class="max-h-80">
                        <flux:table.columns
                            class="bg-white dark:bg-zinc-800"
                            sticky
                        >
                            <flux:table.column class="w-24">{{ __('Locale') }}</flux:table.column>
                            <flux:table.column class="w-36">{{ __('Namespace') }}</flux:table.column>
                            <flux:table.column>{{ __('ui.translation.translation-key') }}</flux:table.column>
                            <flux:table.column>{{ __('Lang key') }}</flux:table.column>
                            <flux:table.column>{{ __('Blocking key') }}</flux:table.column>
                            <flux:table.column>{{ __('Usage') }}</flux:table.column>
                            <flux:table.column>{{ __('Reason') }}</flux:table.column>
                            <flux:table.column align="end">{{ __('ui.actions.actions') }}</flux:table.column>
                        </flux:table.columns>
                        <flux:table.rows>
                            @foreach ($conflicts as $conflict)
                                @php
                                    $blockingFindings = collect($conflict['blocking_findings'] ?? []);
                                    $blockingUsageStatus = (string) ($conflict['blocking_usage_status'] ?? '');
                                    $blockingUsageColor = match ($blockingUsageStatus) {
                                        'active' => 'green',
                                        'obsolete' => 'amber',
                                        'lang_file_only', 'missing_active_usage' => 'red',
                                        default => 'zinc',
                                    };
                                @endphp

                                <flux:table.row>
                                    <flux:table.cell>
                                        <flux:badge
                                            size="sm"
                                            color="red"
                                        >
                                            {{ $conflict['locale'] }}
                                        </flux:badge>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="wrap-anywhere font-mono text-xs">{{ $conflict['namespace'] }}</div>
                                        <div class="wrap-anywhere text-xs text-zinc-500 dark:text-zinc-400">
                                            {{ $conflict['path'] }}</div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="wrap-anywhere font-mono text-xs">{{ $conflict['translation_key'] }}
                                        </div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="wrap-anywhere font-mono text-xs">{{ $conflict['lang_key'] }}</div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="space-y-1">
                                            <div class="wrap-anywhere font-mono text-xs">
                                                {{ $conflict['blocking_translation_key'] ?? __('No matching workbench key') }}
                                            </div>
                                            <div
                                                class="wrap-anywhere font-mono text-xs text-zinc-500 dark:text-zinc-400">
                                                {{ __('Lang key') }}:
                                                {{ $conflict['blocking_lang_key'] ?? '—' }}
                                            </div>
                                            <div class="wrap-anywhere text-xs text-zinc-500 dark:text-zinc-400">
                                                {{ __('Value') }}:
                                                @if (is_array($conflict['blocking_value'] ?? null))
                                                    {{ $conflict['blocking_value']['type'] ?? 'array' }}
                                                    ({{ number_format((int) ($conflict['blocking_value']['count'] ?? 0)) }})
                                                @else
                                                    {{ str((string) ($conflict['blocking_value'] ?? '—'))->limit(80) }}
                                                @endif
                                            </div>
                                        </div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="space-y-1">
                                            <flux:badge
                                                size="sm"
                                                color="{{ $blockingUsageColor }}"
                                            >
                                                {{ $blockingUsageStatus !== '' ? str($blockingUsageStatus)->replace('_', ' ')->title() : __('Unknown') }}
                                            </flux:badge>

                                            @if ($conflict['blocking_key_id'] ?? null)
                                                <div class="font-mono text-xs text-zinc-500 dark:text-zinc-400">
                                                    K#{{ $conflict['blocking_key_id'] }}
                                                </div>
                                            @endif

                                            @if ($conflict['blocking_lang_value_id'] ?? null)
                                                <div class="font-mono text-xs text-zinc-500 dark:text-zinc-400">
                                                    LV#{{ $conflict['blocking_lang_value_id'] }}
                                                </div>
                                            @endif

                                            @if ($blockingFindings->isNotEmpty())
                                                <div class="flex flex-wrap gap-1">
                                                    @foreach ($blockingFindings->take(4) as $finding)
                                                        <flux:badge
                                                            size="sm"
                                                            color="sky"
                                                        >
                                                            F#{{ $finding['id'] ?? '—' }}
                                                        </flux:badge>
                                                    @endforeach
                                                </div>
                                            @endif
                                        </div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <flux:badge
                                            size="sm"
                                            color="red"
                                        >
                                            {{ str($conflict['reason'])->replace('_', ' ')->title() }}
                                        </flux:badge>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <x-ui.tooltip.simple
                                            :title="__('Resolve export conflict')"
                                            :text="__(
                                                'Opens the export conflict context so the blocked write and the blocking existing lang key can be reviewed together.',
                                            )"
                                        >
                                            <flux:button
                                                type="button"
                                                size="xs"
                                                variant="primary"
                                                color="red"
                                                icon="octagon-alert"
                                                wire:click="openExportConflictResolveByKey('{{ $conflict['conflict_key'] }}')"
                                            >
                                                {{ __('Resolve') }}
                                            </flux:button>
                                        </x-ui.tooltip.simple>
                                    </flux:table.cell>
                                </flux:table.row>
                            @endforeach
                        </flux:table.rows>
                    </flux:table>
                </div>
            </flux:callout>
        @endif

        <div class="grid grid-cols-1 gap-3 xl:grid-cols-5">
            @foreach ([['title' => __('Source values'), 'count' => $activeScope['source_values'] ?? 0, 'color' => 'sky', 'icon' => 'languages'], ['title' => __('Target main values'), 'count' => $activeScope['target_main_values'] ?? 0, 'color' => 'green', 'icon' => 'flag'], ['title' => __('ui.target.target-missing'), 'count' => $activeScope['target_main_missing'] ?? 0, 'color' => ($activeScope['target_main_missing'] ?? 0) > 0 ? 'red' : 'green', 'icon' => 'circle-minus'], ['title' => __('Target extras'), 'count' => $activeScope['target_main_extra'] ?? 0, 'color' => ($activeScope['target_main_extra'] ?? 0) > 0 ? 'amber' : 'green', 'icon' => 'circle-plus'], ['title' => __('Sub values'), 'count' => $activeScope['target_sub_values'] ?? 0, 'color' => 'violet', 'icon' => 'git-branch']] as $callout)
                <flux:callout
                    color="{{ $callout['color'] }}"
                    icon="{{ $callout['icon'] }}"
                >
                    <flux:callout.heading>{{ $callout['title'] }}</flux:callout.heading>
                    <flux:callout.text>
                        <span class="text-lg font-semibold tabular-nums">
                            {{ number_format((int) $callout['count']) }}
                        </span>
                    </flux:callout.text>
                </flux:callout>
            @endforeach
        </div>

        <div class="grid grid-cols-1 gap-4 xl:grid-cols-2">
            <flux:callout
                color="{{ $missingKeys->isEmpty() ? 'green' : 'red' }}"
                icon="{{ $missingKeys->isEmpty() ? 'circle-check' : 'circle-minus' }}"
            >
                <flux:callout.heading>
                    {{ __('Source keys without matching target-main translation value') }}
                </flux:callout.heading>
                <flux:callout.text class="min-h-10">
                    {{ __('These source-language translation keys do not have a matching translation value for the active target main language yet.') }}
                </flux:callout.text>

                <div class="mt-3 max-h-80 overflow-y-auto rounded-md border border-zinc-200 dark:border-zinc-700">
                    <flux:table container:class="max-h-80">
                        <flux:table.columns
                            class="bg-white dark:bg-zinc-800"
                            sticky
                        >
                            <flux:table.column
                                class="w-12"
                                align="center"
                            >
                                {{-- <span class="ml-2">{{ __('Find') }}</span> --}}
                                <span class="ml-2">
                                    <flux:icon.search-code />
                                </span>
                            </flux:table.column>
                            <flux:table.column>{{ __('ui.translation.translation-key') }}</flux:table.column>
                            <flux:table.column
                                class="w-12"
                                align="center"
                            >
                                {{-- <span class="mr-3">{{ __('Obsolete') }}</span> --}}
                                <span class="mr-2">
                                    <flux:icon.x class="text-red-500" />
                                </span>
                            </flux:table.column>
                        </flux:table.columns>
                        <flux:table.rows>
                            @forelse ($missingKeys as $key)
                                <flux:table.row>
                                    <flux:table.cell>
                                        <x-ui.tooltip.simple
                                            :title="__('Show in work findings')"
                                            :text="__(
                                                'Filters the Work findings table by this translation key. Exact search stays disabled so related keys with adjusted path segments can still be found.',
                                            )"
                                        >
                                            {{-- Button to show the missing key in the work findings table --}}
                                            <div class="ml-1 text-center">
                                                <flux:button
                                                    class="h-6 w-6"
                                                    type="button"
                                                    size="xs"
                                                    variant="primary"
                                                    color="sky"
                                                    icon="list-filter"
                                                    :aria-label="__('Show in work findings')"
                                                    wire:click="showExportReportKeyInWorkFindings('{{ $key }}')"
                                                />
                                            </div>
                                        </x-ui.tooltip.simple>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="wrap-anywhere font-mono text-xs">{{ $key }}</div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <x-ui.tooltip.simple
                                            :title="__('Review obsolete source value')"
                                            :text="__(
                                                'Opens a focused review before marking the source-language value for this translation key as obsolete. This does not change findings or keys directly.',
                                            )"
                                        >
                                            {{-- Button to review whether this source-language value should be marked obsolete --}}
                                            <div class="mr-2 text-center">
                                                <flux:button
                                                    class="h-6 w-6"
                                                    type="button"
                                                    size="xs"
                                                    variant="primary"
                                                    color="amber"
                                                    icon="archive-x"
                                                    :aria-label="__('Review obsolete source value')"
                                                    wire:click="openObsoleteSourceValueReview('{{ $key }}')"
                                                />
                                            </div>
                                        </x-ui.tooltip.simple>
                                    </flux:table.cell>
                                </flux:table.row>
                            @empty
                                <flux:table.row>
                                    <flux:table.cell
                                        colspan="3"
                                        align="center"
                                    >
                                        <flux:text class="text-sm text-zinc-500">
                                            {{ __('No missing target values.') }}
                                        </flux:text>
                                    </flux:table.cell>
                                </flux:table.row>
                            @endforelse
                        </flux:table.rows>
                    </flux:table>
                </div>
            </flux:callout>

            <flux:callout
                color="{{ $extraKeys->isEmpty() ? 'green' : 'amber' }}"
                icon="{{ $extraKeys->isEmpty() ? 'circle-check' : 'circle-plus' }}"
            >
                <flux:callout.heading>
                    {{ __('Target main values without matching source key') }}
                </flux:callout.heading>
                <flux:callout.text class="min-h-10">
                    {{ __('These active target-main translation values have no matching source-language translation key and should be reviewed as possible leftovers.') }}
                </flux:callout.text>

                <div class="mt-3 max-h-80 overflow-y-auto rounded-md border border-zinc-200 dark:border-zinc-700">
                    <flux:table container:class="max-h-80">
                        <flux:table.columns
                            class="bg-white dark:bg-zinc-800"
                            sticky
                        >
                            <flux:table.column
                                class="w-12"
                                align="center"
                            >
                                <span class="ml-2">{{ __('ui.table.headers.actions') }}</span>
                            </flux:table.column>
                            <flux:table.column>{{ __('ui.translation.translation-key') }}</flux:table.column>
                        </flux:table.columns>
                        <flux:table.rows>
                            @forelse ($extraKeys as $key)
                                <flux:table.row>
                                    <flux:table.cell>
                                        <div class="flex items-center justify-center">
                                            <x-ui.tooltip.simple
                                                :title="__('Show in work findings')"
                                                :text="__(
                                                    'Filters the Work findings table by this exact target-main translation key. Obsolete findings are included so possible leftovers can be found.',
                                                )"
                                            >
                                                {{-- Button to show the extra key in the work findings table --}}
                                                <flux:button
                                                    class="h-6 w-6"
                                                    type="button"
                                                    size="xs"
                                                    variant="primary"
                                                    color="sky"
                                                    icon="list-filter"
                                                    :aria-label="__('Show in work findings')"
                                                    wire:click="showExportReportKeyInWorkFindings('{{ $key }}')"
                                                />
                                            </x-ui.tooltip.simple>
                                        </div>
                                    </flux:table.cell>
                                    <flux:table.cell>
                                        <div class="wrap-anywhere font-mono text-xs">{{ $key }}</div>
                                    </flux:table.cell>
                                </flux:table.row>
                            @empty
                                <flux:table.row>
                                    <flux:table.cell
                                        colspan="2"
                                        align="center"
                                    >
                                        <flux:text class="text-sm text-zinc-500">
                                            {{ __('No target-main values without matching source key.') }}</flux:text>
                                    </flux:table.cell>
                                </flux:table.row>
                            @endforelse
                        </flux:table.rows>
                    </flux:table>
                </div>
            </flux:callout>
        </div>

        <flux:callout
            color="zinc"
            icon="list"
        >
            <flux:callout.heading>{{ __('Values by active locale') }}</flux:callout.heading>
            <div class="mt-3 flex flex-wrap gap-2">
                @forelse ($valuesByLocale as $locale => $count)
                    <flux:badge
                        size="sm"
                        variant="subtle"
                    >
                        {{ $locale }}: {{ number_format((int) $count) }}
                    </flux:badge>
                @empty
                    <flux:text class="text-sm text-zinc-500">{{ __('No locale values reported.') }}</flux:text>
                @endforelse
            </div>
        </flux:callout>
    @endif
</div>
