{{-- packages/gunreip/laravel-translation-workbench/resources/views/livewire/entries/findings/last-run.blade.php --}}

@php
    $report = $pipelineRunReport ?? null;
    $summary = is_array($report['summary'] ?? null) ? $report['summary'] : [];
    $steps = collect($report['steps'] ?? []);
@endphp

<div class="mt-4 space-y-4">
    @if (!$report)
        <flux:callout
            color="amber"
            icon="file-warning"
        >
            <flux:callout.heading>{{ __('No pipeline report found') }}</flux:callout.heading>
            <flux:callout.text>
                {{ __('Run php artisan translation:workbench to generate the pipeline report before reviewing it here.') }}
            </flux:callout.text>
        </flux:callout>
    @else
        <flux:callout
            color="{{ $summary['has_blockers'] ?? false ? 'red' : ($summary['has_stale_reports'] ?? false ? 'amber' : 'green') }}"
            icon="{{ $summary['has_blockers'] ?? false ? 'octagon-alert' : ($summary['has_stale_reports'] ?? false ? 'triangle-alert' : 'circle-check') }}"
        >
            <flux:callout.heading>
                <span class="inline-flex flex-wrap items-center gap-2">
                    <span>{{ __('Last Translation Workbench run') }}</span>
                    <flux:badge
                        size="sm"
                        color="{{ $summary['has_blockers'] ?? false ? 'red' : ($summary['has_stale_reports'] ?? false ? 'amber' : 'green') }}"
                    >
                        {{ $summary['has_blockers'] ?? false ? __('Needs attention') : ($summary['has_stale_reports'] ?? false ? __('Partly stale') : __('Ready')) }}
                    </flux:badge>
                </span>
            </flux:callout.heading>
            <flux:callout.text>
                {{ __('Latest pipeline report generated by :command.', ['command' => $report['command']]) }}
                @if ($report['generated_at'])
                    <span class="ml-1">
                        <x-ui.date-time.date :value="$report['generated_at']" />
                        <x-ui.date-time.time :value="$report['generated_at']" />
                    </span>
                @endif
            </flux:callout.text>
        </flux:callout>

        <div class="grid grid-cols-1 gap-3 xl:grid-cols-5">
            @foreach ([['title' => __('Steps'), 'count' => $summary['steps'] ?? 0, 'color' => 'sky', 'icon' => 'list'], ['title' => __('Fresh reports'), 'count' => $summary['fresh_reports'] ?? 0, 'color' => 'green', 'icon' => 'circle-check'], ['title' => __('Stale reports'), 'count' => $summary['stale_reports'] ?? 0, 'color' => ($summary['stale_reports'] ?? 0) > 0 ? 'amber' : 'zinc', 'icon' => 'triangle-alert'], ['title' => __('Missing reports'), 'count' => $summary['missing_reports'] ?? 0, 'color' => ($summary['missing_reports'] ?? 0) > 0 ? 'red' : 'zinc', 'icon' => 'circle-minus'], ['title' => __('Blockers'), 'count' => $summary['blockers'] ?? 0, 'color' => ($summary['blockers'] ?? 0) > 0 ? 'red' : 'green', 'icon' => 'octagon-alert']] as $callout)
                <flux:callout
                    color="{{ $callout['color'] }}"
                    icon="{{ $callout['icon'] }}"
                >
                    <flux:callout.heading>{{ $callout['title'] }}</flux:callout.heading>
                    <flux:callout.text>
                        <span class="text-lg font-semibold tabular-nums">
                            {{ number_format((int) $callout['count']) }}
                        </span>
                    </flux:callout.text>
                </flux:callout>
            @endforeach
        </div>

        <flux:callout
            color="zinc"
            icon="database"
        >
            <flux:callout.heading>{{ __('Pipeline step reports') }}</flux:callout.heading>
            <flux:callout.text>
                {{ __('Shows the latest report file per pipeline step. Reports marked stale are older than the latest pipeline report and may belong to a previous run.') }}
            </flux:callout.text>

            <div class="mt-3 overflow-x-auto rounded-md border border-zinc-200 dark:border-zinc-700">
                <flux:table>
                    <flux:table.columns
                        class="bg-white dark:bg-zinc-800"
                        sticky
                    >
                        <flux:table.column class="w-12 text-center">#</flux:table.column>
                        <flux:table.column>{{ __('Step') }}</flux:table.column>
                        <flux:table.column>{{ __('Generated') }}</flux:table.column>
                        <flux:table.column>{{ __('ui.state') }}</flux:table.column>
                        <flux:table.column>{{ __('Result') }}</flux:table.column>
                    </flux:table.columns>
                    <flux:table.rows>
                        @foreach ($steps as $step)
                            <flux:table.row>
                                <flux:table.cell class="text-center tabular-nums text-zinc-500">
                                    {{ $step['index'] }}
                                </flux:table.cell>
                                <flux:table.cell>
                                    <div class="min-w-64 space-y-1">
                                        <div class="font-medium">{{ $step['label'] }}</div>
                                        <div class="wrap-anywhere font-mono text-xs text-zinc-500 dark:text-zinc-400">
                                            {{ $step['command'] }}
                                        </div>
                                    </div>
                                </flux:table.cell>
                                <flux:table.cell>
                                    @if ($step['generated_at'])
                                        <div class="whitespace-nowrap text-sm">
                                            <x-ui.date-time.date :value="$step['generated_at']" />
                                            <x-ui.date-time.time :value="$step['generated_at']" />
                                        </div>
                                    @else
                                        <span class="text-sky-500">{{ __('NULL') }}</span>
                                    @endif
                                </flux:table.cell>
                                <flux:table.cell>
                                    <div class="flex flex-wrap gap-1">
                                        <flux:badge
                                            size="sm"
                                            color="{{ $step['state_color'] }}"
                                        >
                                            {{ $step['state_label'] }}
                                        </flux:badge>
                                        @if ($step['write'] ?? false)
                                            <flux:badge
                                                size="sm"
                                                color="green"
                                            >
                                                {{ __('Write') }}
                                            </flux:badge>
                                        @elseif ($step['dry_run'] ?? false)
                                            <flux:badge
                                                size="sm"
                                                color="sky"
                                            >
                                                {{ __('Dry run') }}
                                            </flux:badge>
                                        @endif
                                    </div>
                                </flux:table.cell>
                                <flux:table.cell>
                                    <div class="max-w-4xl space-y-2">
                                        <div class="flex flex-wrap gap-1">
                                            @forelse ($step['metrics'] as $metric)
                                                <flux:badge
                                                    size="sm"
                                                    color="{{ $metric['color'] }}"
                                                >
                                                    {{ $metric['label'] }}:
                                                    <span class="ml-1 tabular-nums">{{ $metric['value'] }}</span>
                                                </flux:badge>
                                            @empty
                                                <span
                                                    class="text-sm text-zinc-500">{{ __('No compact result metrics available.') }}</span>
                                            @endforelse
                                        </div>

                                        @if (!empty($step['notes']))
                                            <div class="space-y-1">
                                                @foreach ($step['notes'] as $note)
                                                    <flux:callout
                                                        color="{{ $note['color'] }}"
                                                        icon="info"
                                                        inline
                                                    >
                                                        <flux:callout.text class="hyphens-auto text-wrap">
                                                            {{ $note['text'] }}
                                                        </flux:callout.text>
                                                    </flux:callout>
                                                @endforeach
                                            </div>
                                        @endif
                                    </div>
                                </flux:table.cell>
                            </flux:table.row>
                        @endforeach
                    </flux:table.rows>
                </flux:table>
            </div>
        </flux:callout>
    @endif
</div>
